import { auth } from "@/auth";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Navbar from "../components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Admin Page",
  description: "Generated by create next app",
};

export default async function AuthinticateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session?.user) {
    return redirect("/login");
  }

  return (
    <div className="w-full h-screen flex flex-col ">
      <Navbar session={session}/>
      <div className="flex-grow">{children}</div>
    </div>
  );
}
