import { auth } from "@/auth";
import type { Metadata } from "next";
import Navbar from "../components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function AuthinticateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await auth();

  return (
    <div className="w-full h-screen flex flex-col ">
      <Navbar session={session} />{}
      <div className="flex-grow">{children}</div>
    </div>
  );
}
